# Generated by Django 6.0.2 on 2026-03-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
