# Generated by Django 6.0.2 on 2026-04-12 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('jobs', '0001_initial'),
        ('users', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_job_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_cards', to='vehicles.customer'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_job_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_cards', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_cards', to='users.workshop'),
        ),
        migrations.AddField(
            model_name='jobcardpart',
            name='issued_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobcardpart',
            name='job_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='jobs.jobcard'),
        ),
        migrations.AddField(
            model_name='jobcardpart',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_card_uses', to='inventory.productvariant'),
        ),
        migrations.AddField(
            model_name='jobcardservice',
            name='job_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='jobs.jobcard'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='job_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='jobs.jobcard'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='moved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.productvariant'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='inventory.purchaseorder'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='users.workshop'),
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['workshop', 'status'], name='jobs_jobcar_worksho_b48bf1_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['workshop', 'created_at'], name='jobs_jobcar_worksho_3e3a13_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['workshop', 'product_variant'], name='jobs_stockm_worksho_26bb2f_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['workshop', 'movement_type'], name='jobs_stockm_worksho_f99494_idx'),
        ),
    ]
