# Generated by Django 6.0.2 on 2026-04-12 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('users', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.workshop'),
        ),
        migrations.AddField(
            model_name='category',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.workshop'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.workshop'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.workshop'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.brand'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='compatible_vehicles',
            field=models.ManyToManyField(blank=True, to='vehicles.vehiclemodel'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.workshop'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='inventory.productvariant'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='users.workshop'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_items', to='inventory.productvariant'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseorder'),
        ),
        migrations.AddField(
            model_name='stock',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='inventory.productvariant'),
        ),
        migrations.AddField(
            model_name='stock',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.workshop'),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_setting', to='inventory.productvariant'),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='users.workshop'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='users.workshop'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('name', 'workshop')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'workshop')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['workshop'], name='inventory_p_worksho_6d2529_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'category', 'workshop')},
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['workshop'], name='inventory_p_worksho_eee807_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['sku'], name='inventory_p_sku_3e98d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('sku', 'workshop')},
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('product_variant', 'workshop')},
        ),
        migrations.AlterUniqueTogether(
            name='stockalert',
            unique_together={('product_variant', 'workshop')},
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('name', 'workshop')},
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['workshop', 'status'], name='inventory_p_worksho_8b7d9b_idx'),
        ),
    ]
