# Generated by Django 6.0.2 on 2026-03-26 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.workshop'),
        ),
        migrations.AddField(
            model_name='category',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.workshop'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.workshop'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.brand'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.workshop'),
        ),
        migrations.AddField(
            model_name='stock',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productvariant'),
        ),
        migrations.AddField(
            model_name='stock',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.workshop'),
        ),
        migrations.AddField(
            model_name='vehiclebrand',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.workshop'),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.vehiclebrand'),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.workshop'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='compatible_vehicles',
            field=models.ManyToManyField(blank=True, to='inventory.vehiclemodel'),
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('name', 'workshop')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'workshop')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['workshop'], name='inventory_p_worksho_6d2529_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'category', 'workshop')},
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('product_variant', 'workshop')},
        ),
        migrations.AlterUniqueTogether(
            name='vehiclebrand',
            unique_together={('name', 'workshop')},
        ),
        migrations.AlterUniqueTogether(
            name='vehiclemodel',
            unique_together={('brand', 'model_name', 'workshop')},
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['workshop'], name='inventory_p_worksho_eee807_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['sku'], name='inventory_p_sku_3e98d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('sku', 'workshop')},
        ),
    ]
