# Generated by Django 6.0.2 on 2026-04-12 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='users.workshop')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(choices=[('2W', 'Two Wheeler'), ('3W', 'Three Wheeler'), ('4W', 'Four Wheeler'), ('HV', 'Heavy Vehicle')], default='2W', max_length=2)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='vehicles.vehiclebrand')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(max_length=20)),
                ('chassis_no', models.CharField(blank=True, max_length=50)),
                ('engine_no', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(blank=True, choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Electric'), ('CNG', 'CNG')], max_length=10)),
                ('odometer_km', models.PositiveIntegerField(default=0)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('puc_expiry', models.DateField(blank=True, null=True)),
                ('permit_expiry', models.DateField(blank=True, null=True)),
                ('fitness_expiry', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='vehicles.customer')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='users.workshop')),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_vehicles', to='vehicles.vehiclemodel')),
            ],
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['workshop', 'phone'], name='vehicles_cu_worksho_09a36f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('phone', 'workshop')},
        ),
        migrations.AlterUniqueTogether(
            name='vehiclebrand',
            unique_together={('name', 'workshop')},
        ),
        migrations.AlterUniqueTogether(
            name='vehiclemodel',
            unique_together={('brand', 'model_name', 'workshop')},
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['workshop', 'registration_no'], name='vehicles_ve_worksho_f95834_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('registration_no', 'workshop')},
        ),
    ]
